linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - goconst
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck

linters-settings:
  misspell:
    locale: US

run:
  build-tags:
    - integration
  deadline: 5m
